// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TIME_SHIFTED_SERVICE_ODB_H
#define TIME_SHIFTED_SERVICE_ODB_H

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "TimeShiftedService.h"

#include "TsSvcId-odb.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // TimeShiftedService
  //
  template <>
  struct class_traits< ::TimeShiftedService >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::TimeShiftedService >
  {
    public:
    typedef ::TimeShiftedService object_type;
    typedef ::std::shared_ptr< ::TimeShiftedService > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::TsSvcId id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // TimeShiftedServiceEvent
  //
  template <>
  struct class_traits< ::TimeShiftedServiceEvent >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::TimeShiftedServiceEvent >
  {
    public:
    typedef ::TimeShiftedServiceEvent object_type;
    typedef ::std::shared_ptr< ::TimeShiftedServiceEvent > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::TableIndex id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // TimeShiftedService
  //
  template <typename A>
  struct query_columns< ::TimeShiftedService, id_mysql, A >
  {
    // tmssId
    //
    struct tmssId_class_
    {
      tmssId_class_ ()
      {
      }

      // tsId
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::TsId,
          mysql::id_ushort >::query_type,
        mysql::id_ushort >
      tsId_type_;

      static const tsId_type_ tsId;

      // serviceId
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::ServiceId,
          mysql::id_ushort >::query_type,
        mysql::id_ushort >
      serviceId_type_;

      static const serviceId_type_ serviceId;
    };

    static const tmssId_class_ tmssId;

    // description
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    description_type_;

    static const description_type_ description;
  };

  template <typename A>
  const typename query_columns< ::TimeShiftedService, id_mysql, A >::tmssId_class_::tsId_type_
  query_columns< ::TimeShiftedService, id_mysql, A >::tmssId_class_::
  tsId (A::table_name, "`TmssId_TsId`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedService, id_mysql, A >::tmssId_class_::serviceId_type_
  query_columns< ::TimeShiftedService, id_mysql, A >::tmssId_class_::
  serviceId (A::table_name, "`TmssId_SvcId`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedService, id_mysql, A >::tmssId_class_
  query_columns< ::TimeShiftedService, id_mysql, A >::tmssId;

  template <typename A>
  const typename query_columns< ::TimeShiftedService, id_mysql, A >::description_type_
  query_columns< ::TimeShiftedService, id_mysql, A >::
  description (A::table_name, "`Description`", 0);

  template <typename A>
  struct pointer_query_columns< ::TimeShiftedService, id_mysql, A >:
    query_columns< ::TimeShiftedService, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::TimeShiftedService, id_mysql >:
    public access::object_traits< ::TimeShiftedService >
  {
    public:
    struct id_image_type
    {
      composite_value_traits< ::TsSvcId, id_mysql >::image_type id_value;

      std::size_t version;
    };

    struct image_type
    {
      // tmssId
      //
      composite_value_traits< ::TsSvcId, id_mysql >::image_type tmssId_value;

      // description
      //
      details::buffer description_value;
      unsigned long description_size;
      my_bool description_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // events
    //
    struct events_traits
    {
      static const std::size_t id_column_count = 2UL;
      static const std::size_t data_column_count = 3UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::TimeShiftedService::EventsType container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef mysql::container_statements< events_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        unsigned int value_value;
        my_bool value_null;

        std::size_t version;
      };

      static void
      bind (MYSQL_BIND*,
            const MYSQL_BIND* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            my_bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 2UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::TimeShiftedService, id_common >:
    public access::object_traits_impl< ::TimeShiftedService, id_mysql >
  {
  };

  // TimeShiftedServiceEvent
  //
  template <typename A>
  struct pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >
  {
    // idx
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TableIndex,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    idx_type_;

    static const idx_type_ idx;

    // eventId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::EventId,
        mysql::id_ushort >::query_type,
      mysql::id_ushort >
    eventId_type_;

    static const eventId_type_ eventId;

    // posterId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::PosterId,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    posterId_type_;

    static const posterId_type_ posterId;

    // startTimePoint
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TimePoint,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    startTimePoint_type_;

    static const startTimePoint_type_ startTimePoint;

    // duration
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::Seconds,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    duration_type_;

    static const duration_type_ duration;

    // tmss
    //
    struct tmss_class_
    {
      tmss_class_ ()
      {
      }

      // tsId
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::TsId,
          mysql::id_ushort >::query_type,
        mysql::id_ushort >
      tsId_type_;

      static const tsId_type_ tsId;

      // serviceId
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::ServiceId,
          mysql::id_ushort >::query_type,
        mysql::id_ushort >
      serviceId_type_;

      static const serviceId_type_ serviceId;
    };

    static const tmss_class_ tmss;
  };

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::idx_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  idx (A::table_name, "`Idx`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::eventId_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  eventId (A::table_name, "`EventId`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::posterId_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  posterId (A::table_name, "`PosterId`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::startTimePoint_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  startTimePoint (A::table_name, "`StartTimePoint`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::duration_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  duration (A::table_name, "`Duration`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_class_::tsId_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_class_::
  tsId (A::table_name, "`Tmss_TsId`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_class_::serviceId_type_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_class_::
  serviceId (A::table_name, "`Tmss_SvcId`", 0);

  template <typename A>
  const typename pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_class_
  pointer_query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss;

  template <>
  class access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >:
    public access::object_traits< ::TimeShiftedServiceEvent >
  {
    public:
    struct id_image_type
    {
      unsigned int id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // idx
      //
      unsigned int idx_value;
      my_bool idx_null;

      // eventId
      //
      unsigned short eventId_value;
      my_bool eventId_null;

      // posterId
      //
      unsigned int posterId_value;
      my_bool posterId_null;

      // startTimePoint
      //
      unsigned long long startTimePoint_value;
      my_bool startTimePoint_null;

      // duration
      //
      unsigned long long duration_value;
      my_bool duration_null;

      // tmss
      //
      composite_value_traits< ::TsSvcId, id_mysql >::image_type tmss_value;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct tmss_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::TimeShiftedServiceEvent, id_common >:
    public access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >
  {
  };

  // TimeShiftedService
  //
  // TimeShiftedServiceEvent
  //
  template <>
  struct alias_traits<
    ::TimeShiftedService,
    id_mysql,
    access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::tmss_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::TimeShiftedServiceEvent, id_mysql >
  {
    // tmss
    //
    typedef
    odb::alias_traits<
      ::TimeShiftedService,
      id_mysql,
      access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::tmss_tag>
    tmss_alias_;
  };

  template <typename A>
  struct query_columns< ::TimeShiftedServiceEvent, id_mysql, A >:
    query_columns_base< ::TimeShiftedServiceEvent, id_mysql >
  {
    // idx
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TableIndex,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    idx_type_;

    static const idx_type_ idx;

    // eventId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::EventId,
        mysql::id_ushort >::query_type,
      mysql::id_ushort >
    eventId_type_;

    static const eventId_type_ eventId;

    // posterId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::PosterId,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    posterId_type_;

    static const posterId_type_ posterId;

    // startTimePoint
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TimePoint,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    startTimePoint_type_;

    static const startTimePoint_type_ startTimePoint;

    // duration
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::Seconds,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    duration_type_;

    static const duration_type_ duration;

    // tmss
    //
    struct tmss_column_class_
    {
      tmss_column_class_ ()
      {
      }

      // tsId
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::TsId,
          mysql::id_ushort >::query_type,
        mysql::id_ushort >
      tsId_type_;

      static const tsId_type_ tsId;

      // serviceId
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::ServiceId,
          mysql::id_ushort >::query_type,
        mysql::id_ushort >
      serviceId_type_;

      static const serviceId_type_ serviceId;
    };

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::TimeShiftedService,
        id_mysql,
        tmss_alias_ > >
    tmss_pointer_type_;

    struct tmss_type_: tmss_pointer_type_, tmss_column_class_
    {
      tmss_type_ ()
      {
      }
    };

    static const tmss_type_ tmss;
  };

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::idx_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  idx (A::table_name, "`Idx`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::eventId_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  eventId (A::table_name, "`EventId`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::posterId_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  posterId (A::table_name, "`PosterId`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::startTimePoint_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  startTimePoint (A::table_name, "`StartTimePoint`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::duration_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::
  duration (A::table_name, "`Duration`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_column_class_::tsId_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_column_class_::
  tsId (A::table_name, "`Tmss_TsId`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_column_class_::serviceId_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_column_class_::
  serviceId (A::table_name, "`Tmss_SvcId`", 0);

  template <typename A>
  const typename query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss_type_
  query_columns< ::TimeShiftedServiceEvent, id_mysql, A >::tmss;
}

#include "TimeShiftedService-odb.ixx"

#include <odb/post.hxx>

#endif // TIME_SHIFTED_SERVICE_ODB_H
