// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "TimeShiftedService-odb.h"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // TimeShiftedService
  //

  struct access::object_traits_impl< ::TimeShiftedService, id_mysql >::extra_statement_cache_type
  {
    mysql::container_statements_impl< events_traits > events;

    extra_statement_cache_type (
      mysql::connection& c,
      image_type&,
      id_image_type&,
      mysql::binding& id,
      mysql::binding&)
    : events (c, id)
    {
    }
  };

  // events
  //

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  select_statement[] =
  "SELECT "
  "`TimeShiftedServiceEvent`.`Idx` "
  "FROM `TimeShiftedServiceEvent` "
  "WHERE `TimeShiftedServiceEvent`.`Tmss_TsId`=? AND `TimeShiftedServiceEvent`.`Tmss_SvcId`=?";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  insert_statement[] =
  "";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  delete_statement[] =
  "";

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // value
    //
    t[0UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  init (value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      typedef object_traits< ::TimeShiftedServiceEvent > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));

        if (odb::pointer_traits<ptr_traits::strong_pointer_type>::null_ptr (
              ptr_traits::lock (v)))
          throw session_required ();
      }
    }
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  insert (index_type, const value_type&, void*)
  {
  }

  bool access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  select (index_type&, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  delete_ (void*)
  {
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::events_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = false;
    container_traits_type::load (c, more, fs);
  }

  access::object_traits_impl< ::TimeShiftedService, id_mysql >::id_type
  access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::TsSvcId, id_mysql >::init (
        id,
        i.tmssId_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // tmssId
    //
    if (composite_value_traits< ::TsSvcId, id_mysql >::grow (
          i.tmssId_value, t + 0UL))
      grew = true;

    // description
    //
    if (t[2UL])
    {
      i.description_value.capacity (i.description_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // tmssId
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::TsSvcId, id_mysql >::bind (
        b + n, i.tmssId_value, sk);
      n += 2UL;
    }

    // description
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.description_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.description_value.capacity ());
    b[n].length = &i.description_size;
    b[n].is_null = &i.description_null;
    n++;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    mysql::statement_kind sk (mysql::statement_select);
    composite_value_traits< ::TsSvcId, id_mysql >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // tmssId
    //
    if (sk == statement_insert)
    {
      // From TimeShiftedService.h:51:36
      ::TsSvcId const& v =
        o.GetTmssId ();

      composite_value_traits< ::TsSvcId, id_mysql >::init (
        i.tmssId_value,
        v,
        sk);
    }

    // description
    //
    {
      // From TimeShiftedService.h:54:38
      ::std::string const& v =
        o.GetDescription ();

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.description_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.description_value,
        size,
        is_null,
        v);
      i.description_null = is_null;
      i.description_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.description_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // tmssId
    //
    {
      // From TimeShiftedService.h:51:51
      ::TsSvcId v;

      composite_value_traits< ::TsSvcId, id_mysql >::init (
        v,
        i.tmssId_value,
        db);

      // From TimeShiftedService.h:51:51
      o.SetTmssId (v);
    }

    // description
    //
    {
      // From TimeShiftedService.h:54:58
      ::std::string v;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.description_value,
        i.description_size,
        i.description_null);

      // From TimeShiftedService.h:54:58
      o.SetDescription (v);
    }
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    mysql::statement_kind sk (mysql::statement_select);
    {
      composite_value_traits< ::TsSvcId, id_mysql >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::persist_statement[] =
  "INSERT INTO `TimeShiftedService` "
  "(`TmssId_TsId`, "
  "`TmssId_SvcId`, "
  "`Description`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::find_statement[] =
  "SELECT "
  "`TimeShiftedService`.`TmssId_TsId`, "
  "`TimeShiftedService`.`TmssId_SvcId`, "
  "`TimeShiftedService`.`Description` "
  "FROM `TimeShiftedService` "
  "WHERE `TimeShiftedService`.`TmssId_TsId`=? AND `TimeShiftedService`.`TmssId_SvcId`=?";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::update_statement[] =
  "UPDATE `TimeShiftedService` "
  "SET "
  "`Description`=? "
  "WHERE `TmssId_TsId`=? AND `TmssId_SvcId`=?";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::erase_statement[] =
  "DELETE FROM `TimeShiftedService` "
  "WHERE `TmssId_TsId`=? AND `TmssId_SvcId`=?";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::query_statement[] =
  "SELECT "
  "`TimeShiftedService`.`TmssId_TsId`, "
  "`TimeShiftedService`.`TmssId_SvcId`, "
  "`TimeShiftedService`.`Description` "
  "FROM `TimeShiftedService`";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::erase_query_statement[] =
  "DELETE FROM `TimeShiftedService`";

  const char access::object_traits_impl< ::TimeShiftedService, id_mysql >::table_name[] =
  "`TimeShiftedService`";

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    // From TimeShiftedService.h:51:36
    const id_type& id (
      obj.GetTmssId ());
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TimeShiftedService, id_mysql >::pointer_type
  access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    // From TimeShiftedService.h:51:36
    const id_type& id  (
      obj.GetTmssId ());

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // events
    //
    {
      // From TimeShiftedService.h:57:60
      ::TimeShiftedService::EventsType v;

      events_traits::load (
        v,
        esc.events);

      // From TimeShiftedService.h:57:60
      obj.SetEvents (v);
    }
  }

  result< access::object_traits_impl< ::TimeShiftedService, id_mysql >::object_type >
  access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TimeShiftedService, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // TimeShiftedServiceEvent
  //

  const char alias_traits<  ::TimeShiftedService,
    id_mysql,
    access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::tmss_tag>::
  table_name[] = "`Tmss`";

  struct access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::id_type
  access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::TableIndex,
          mysql::id_ulong >::set_value (
        id,
        i.idx_value,
        i.idx_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // idx
    //
    t[0UL] = 0;

    // eventId
    //
    t[1UL] = 0;

    // posterId
    //
    t[2UL] = 0;

    // startTimePoint
    //
    t[3UL] = 0;

    // duration
    //
    t[4UL] = 0;

    // tmss
    //
    if (composite_value_traits< ::TsSvcId, id_mysql >::grow (
          i.tmss_value, t + 5UL))
      grew = true;

    return grew;
  }

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // idx
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.idx_value;
      b[n].is_null = &i.idx_null;
      n++;
    }

    // eventId
    //
    b[n].buffer_type = MYSQL_TYPE_SHORT;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.eventId_value;
    b[n].is_null = &i.eventId_null;
    n++;

    // posterId
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.posterId_value;
    b[n].is_null = &i.posterId_null;
    n++;

    // startTimePoint
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.startTimePoint_value;
    b[n].is_null = &i.startTimePoint_null;
    n++;

    // duration
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.duration_value;
    b[n].is_null = &i.duration_null;
    n++;

    // tmss
    //
    composite_value_traits< ::TsSvcId, id_mysql >::bind (
      b + n, i.tmss_value, sk);
    n += 2UL;
  }

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // idx
    //
    if (sk == statement_insert)
    {
      // From TimeShiftedService.h:95:30
      ::TableIndex const& v =
        o.GetIndex ();

      bool is_null (false);
      mysql::value_traits<
          ::TableIndex,
          mysql::id_ulong >::set_image (
        i.idx_value, is_null, v);
      i.idx_null = is_null;
    }

    // eventId
    //
    {
      // From TimeShiftedService.h:98:34
      ::EventId const& v =
        o.GetEventId ();

      bool is_null (false);
      mysql::value_traits<
          ::EventId,
          mysql::id_ushort >::set_image (
        i.eventId_value, is_null, v);
      i.eventId_null = is_null;
    }

    // posterId
    //
    {
      // From TimeShiftedService.h:100:35
      ::PosterId const& v =
        o.GetPosterId ();

      bool is_null (false);
      mysql::value_traits<
          ::PosterId,
          mysql::id_ulong >::set_image (
        i.posterId_value, is_null, v);
      i.posterId_null = is_null;
    }

    // startTimePoint
    //
    {
      // From TimeShiftedService.h:102:41
      ::TimePoint const& v =
        o.GetStartTimePoint ();

      bool is_null (false);
      mysql::value_traits<
          ::TimePoint,
          mysql::id_ulonglong >::set_image (
        i.startTimePoint_value, is_null, v);
      i.startTimePoint_null = is_null;
    }

    // duration
    //
    {
      // From TimeShiftedService.h:104:35
      ::Seconds const& v =
        o.GetDuration ();

      bool is_null (false);
      mysql::value_traits<
          ::Seconds,
          mysql::id_ulonglong >::set_image (
        i.duration_value, is_null, v);
      i.duration_null = is_null;
    }

    // tmss
    //
    {
      // From TimeShiftedService.h:107:40
      ::TimeShiftedServiceEvent::TmssPtrType const& v =
        o.GetTimeShiftedService ();

      typedef object_traits< ::TimeShiftedService > obj_traits;
      typedef odb::pointer_traits< ::TimeShiftedServiceEvent::TmssPtrType > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        composite_value_traits< obj_traits::id_type, id_mysql >::init (
          i.tmss_value,
          id,
          sk);
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // idx
    //
    {
      // From TimeShiftedService.h:95:44
      ::TableIndex v;

      mysql::value_traits<
          ::TableIndex,
          mysql::id_ulong >::set_value (
        v,
        i.idx_value,
        i.idx_null);

      // From TimeShiftedService.h:95:44
      o.SetIndex (v);
    }

    // eventId
    //
    {
      // From TimeShiftedService.h:98:50
      ::EventId v;

      mysql::value_traits<
          ::EventId,
          mysql::id_ushort >::set_value (
        v,
        i.eventId_value,
        i.eventId_null);

      // From TimeShiftedService.h:98:50
      o.SetEventId (v);
    }

    // posterId
    //
    {
      // From TimeShiftedService.h:100:52
      ::PosterId v;

      mysql::value_traits<
          ::PosterId,
          mysql::id_ulong >::set_value (
        v,
        i.posterId_value,
        i.posterId_null);

      // From TimeShiftedService.h:100:52
      o.SetPosterId (v);
    }

    // startTimePoint
    //
    {
      // From TimeShiftedService.h:102:64
      ::TimePoint v;

      mysql::value_traits<
          ::TimePoint,
          mysql::id_ulonglong >::set_value (
        v,
        i.startTimePoint_value,
        i.startTimePoint_null);

      // From TimeShiftedService.h:102:64
      o.SetStartTimePoint (v);
    }

    // duration
    //
    {
      // From TimeShiftedService.h:104:52
      ::Seconds v;

      mysql::value_traits<
          ::Seconds,
          mysql::id_ulonglong >::set_value (
        v,
        i.duration_value,
        i.duration_null);

      // From TimeShiftedService.h:104:52
      o.SetDuration (v);
    }

    // tmss
    //
    {
      // From TimeShiftedService.h:107:67
      ::TimeShiftedServiceEvent::TmssPtrType v;

      typedef object_traits< ::TimeShiftedService > obj_traits;
      typedef odb::pointer_traits< ::TimeShiftedServiceEvent::TmssPtrType > ptr_traits;

      if (composite_value_traits< obj_traits::id_type, id_mysql >::get_null (
            i.tmss_value))
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        composite_value_traits< obj_traits::id_type, id_mysql >::init (
          id,
          i.tmss_value,
          db);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }

      // From TimeShiftedService.h:107:67
      o.SetTimeShiftedService (v);
    }
  }

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::TableIndex,
          mysql::id_ulong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::persist_statement[] =
  "INSERT INTO `TimeShiftedServiceEvent` "
  "(`Idx`, "
  "`EventId`, "
  "`PosterId`, "
  "`StartTimePoint`, "
  "`Duration`, "
  "`Tmss_TsId`, "
  "`Tmss_SvcId`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::find_statement[] =
  "SELECT "
  "`TimeShiftedServiceEvent`.`Idx`, "
  "`TimeShiftedServiceEvent`.`EventId`, "
  "`TimeShiftedServiceEvent`.`PosterId`, "
  "`TimeShiftedServiceEvent`.`StartTimePoint`, "
  "`TimeShiftedServiceEvent`.`Duration`, "
  "`TimeShiftedServiceEvent`.`Tmss_TsId`, "
  "`TimeShiftedServiceEvent`.`Tmss_SvcId` "
  "FROM `TimeShiftedServiceEvent` "
  "WHERE `TimeShiftedServiceEvent`.`Idx`=?";

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::update_statement[] =
  "UPDATE `TimeShiftedServiceEvent` "
  "SET "
  "`EventId`=?, "
  "`PosterId`=?, "
  "`StartTimePoint`=?, "
  "`Duration`=?, "
  "`Tmss_TsId`=?, "
  "`Tmss_SvcId`=? "
  "WHERE `Idx`=?";

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::erase_statement[] =
  "DELETE FROM `TimeShiftedServiceEvent` "
  "WHERE `Idx`=?";

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::query_statement[] =
  "SELECT\n"
  "`TimeShiftedServiceEvent`.`Idx`,\n"
  "`TimeShiftedServiceEvent`.`EventId`,\n"
  "`TimeShiftedServiceEvent`.`PosterId`,\n"
  "`TimeShiftedServiceEvent`.`StartTimePoint`,\n"
  "`TimeShiftedServiceEvent`.`Duration`,\n"
  "`TimeShiftedServiceEvent`.`Tmss_TsId`,\n"
  "`TimeShiftedServiceEvent`.`Tmss_SvcId`\n"
  "FROM `TimeShiftedServiceEvent`\n"
  "LEFT JOIN `TimeShiftedService` AS `Tmss` ON `Tmss`.`TmssId_TsId`=`TimeShiftedServiceEvent`.`Tmss_TsId` AND `Tmss`.`TmssId_SvcId`=`TimeShiftedServiceEvent`.`Tmss_SvcId`";

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::erase_query_statement[] =
  "DELETE FROM `TimeShiftedServiceEvent`";

  const char access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::table_name[] =
  "`TimeShiftedServiceEvent`";

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    // From TimeShiftedService.h:95:30
    const id_type& id (
      obj.GetIndex ());
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::pointer_type
  access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    // From TimeShiftedService.h:95:30
    const id_type& id  (
      obj.GetIndex ());

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::object_type >
  access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TimeShiftedServiceEvent, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
